import React, { useEffect } from "react";
import { Col, Container, Row } from "react-bootstrap";

const TermsOfUse = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <Container>
      <Row className="my-5">
        <p className="fs-3 text-white">Terms OF Use</p>
        <Col className="text-gray-400">
          Last updated: November 27, 2023 This document is an electronic record
          in terms of the Information Technology Act, 2000 and rules there under
          as applicable and various other statutes. This electronic record is
          generated by a computer system and does not require any physical or
          digital signatures. This is a legal and binding agreement between you,
          the user ("User" or "You") of the Services, as defined below, and Novi
          Digital Entertainment Private Limited (formerly known as Indya
          Interactive Services Private Limited) stating the terms that govern
          Your use of the Site (as defined below), as defined below. BY
          ACCEPTING THESE TERMS OF USE IN ANY MANNER OR ACCESSING THIS WEBSITE,
          YOU CONSENT, AGREE AND UNDERTAKE TO ABIDE, BE BOUND BY AND ADHERE TO
          THE TERMS OF USE and the Privacy Policy accessible at
          www.hotstar.com/terms-of-use and www.hotstar.com/privacy-policy
          respectively and any other terms which govern the Site (together
          referred to as "Terms of Use" or "Terms" or "Terms and Conditions")
          AND IF YOU DO NOT AGREE TO THESE TERMS OF USE, YOU ARE NOT ENTITLED TO
          AVAIL OF / USE THE SERVICES AND ANY USE THEREAFTER SHALL BE
          UNAUTHORIZED. Description of Service and Acceptance of Terms of Use
          Novi Digital Entertainment Private Limited (formerly known as Indya
          Interactive Services Private Limited) is a company incorporated under
          the Companies Act, 1956, having its registered office at STAR House,
          Urmi Estate, 95 Ganpatrao Kadam Marg, Lower Parel (West), Mumbai-
          400013, India ("Novi"). Novi inter alia provides an online website
          'www.hotstar.com ' as an interactive platform for its viewers and any
          associated mobile sites, applications, games ("Site") to inter alia
          view serials and programs, films, sports content including live sports
          content, trailers of upcoming serials, view videos and/or photos of
          their favourite characters on serials, read recaps of serials,
          international content including viewing schedules of content offered,
          provide interactive games plays etc. on or through the Site and any
          other features, tools, applications, materials, or other services
          offered from time to time by Novi in connection with its business,
          provided on or through the Site ("Novi Content"). For some Novi
          Content, Novi may enable gaming and/or an interactive chat feature
          which may provide various features to the User(s) including but not
          limited to posting of comments, videos, pictures and participation in
          contests (“Social Feed”). The Site may also provide you content by
          integrating services and application of other audio video streaming
          platforms (“Partner Content”) and/or provide hosting service to third
          parties to display and allow access to their content and interactive
          games etc. (“Third Party Content”). Novi may also provide standalone
          games and/or other forms of interactive engagement features on or
          through the Site (“Gaming Content”). ‘Content’ will hence consist of
          ‘Novi Content’, Partner Content, ‘‘Third Party Content’ and/or any
          Gaming Content made available by Novi. All such features of the Site
          collectively referred to as “Services”). The Content will be made
          available to You through different modes, at the discretion of Novi,
          including via video on demand basis for viewing at the User's
          discretion at a time chosen by You and download for offline viewing by
          You or through a separate standalone Site or mobile Application. In
          the case of downloadable Content (not being a Gaming Content or a
          standalone mobile application / Site), please note that: (a) the
          downloads are temporary in order to allow you to view the Content
          within a specified period of time and you shall not attempt to or
          actually make a permanent copy of the Content in any manner or form,
          and (b) not all Content may be available for download for offline
          viewing. Please note that the availability of, and Your ability to
          access, the Content or some part of Services, (a) is subject to Novi's
          sole discretion and (b) may be dependent upon Your geographical
          location and (c) is on the condition that not all Content or Services
          will be available to all viewers. On account of the nature of the
          Internet, this Site and the Services may also be accessed in various
          geographical locations; and You hereby agree and acknowledge that You
          are accessing this Site and availing of the Services, at Your own
          risk, choice and initiative and You agree and undertake to ensure that
          Your use of the Site and the Services complies with all applicable
          laws including the local laws in Your jurisdiction. Further, such
          Services and Content may vary from place to place, time to time and
          device to device and would be subject to various parameters such as
          specifications, device, Internet availability and speed, bandwidth,
          etc. You agree and acknowledge that Novi may monitor or use certain
          technologies for monitoring of activities, as separately explained in
          Novi’s Privacy Policy. To facilitate Your viewership and access, the
          Services can be packaged by Novi through different models such as,
          Content or Services may be accessible (a) free of charge which may
          include advertisements or commercials or (b) via subscription through
          payment of a subscription fee as per the relevant subscription plan
          selected or (c) a pay-per-view model with or without
          advertisements/commercials or (d) with a combination of the foregoing
          on the Site. Note that Some Content such as live sports or shows, when
          accessed, will show advertisements even where the subscription plan
          selected is an advertisement free plan. The Service can be availed
          through platforms, software and devices, which Novi approves from time
          to time, the current list for which is as set out below ("Compatible
          System"). In some cases, whether a device is (or remains) a Compatible
          System may depend on software or platform provided or maintained by
          the device manufacturer or other third parties. As a result, devices
          that are Compatible System at one time may cease to be Compatible
          System in the future. The Disney+ Hotstar website works best with: ·
          Latest version of Google Chrome · Latest version of Firefox · Latest
          version of Safari · Microsoft Windows XP or above / MAC OS 10.2 or
          above · Latest version of Adobe Flash Player · JavaScript and cookies
          enabled The Disney+ Hotstar applications work best with a minimum
          system requirement of: · Android 4.4.4 · iOS 10.0 · AndroidTV -
          Android 7.1.1 The Dahan game application works best with a minimum
          system requirement of: · Android 4.4.4 · iOS 10.0
        </Col>
      </Row>
    </Container>
  );
};

export default TermsOfUse;
